quarkus.datasource.db-kind=pg
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.min-size=10

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Security, JWT and related.
mp.jwt.verify.publickey.algorithm=ES256
mp.jwt.verify.publickey.location=${JWT_JWKS_URL}
mp.jwt.verify.issuer=${JWT_ISSUER}

quarkus.http.auth.permission.public-ws.paths=/ws/*
quarkus.http.auth.permission.public-ws.policy=permit

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.public-cors.paths=/*
quarkus.http.auth.permission.public-cors.methods=OPTIONS
quarkus.http.auth.permission.public-cors.policy=permit

# Supabase Admin API
supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}

# WebSocket settings
quarkus.websocket.max-frame-size=10485760
quarkus.log.level=INFO
quarkus.log.category."com.frieren".level=DEBUG
